# Generated by Django 4.0.1 on 2022-02-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_zetuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zetuser',
            options={'ordering': ('username',), 'verbose_name': 'Zet User', 'verbose_name_plural': 'Zet Users'},
        ),
    ]
