#version: '3'
#services:

#  redis:
#    container_name: zetpass_redis
#    image: redis:4-alpine
#    volumes:
#      - /var/lib/redis/data:/data
#    ports:
#      - "127.0.0.1:6379:6379"
#    # run in persistent mode
#    command: redis-server --appendonly yes
#    restart: always

  postgres:
    container_name: zetpass_db
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file: .env
