# Generated by Django 4.0.1 on 2022-02-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_options', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('encrypted_app_id', models.CharField(blank=True, max_length=64, verbose_name='ID of client or app')),
                ('encrypted_token', models.CharField(max_length=300, verbose_name='Token')),
                ('allowed_ips', models.ManyToManyField(related_name='tokens', to='access_options.UserIP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_login', models.CharField(db_index=True, max_length=100, verbose_name='Encrypted login, email or ID')),
                ('encrypted_password', models.CharField(max_length=300, verbose_name='Encrypted password')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='credentials.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('encrypted_text', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('expired_public_at', models.DateTimeField(auto_now=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('links_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='credentials.links')),
            ],
        ),
    ]
